In [1]:
!pip install emoji


[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [42]:
from tracemalloc import stop
import numpy as np
import pandas as pd
import re
import seaborn as sns
import string
import nltk
import emoji
import string
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
import string

In [3]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [4]:
nltk.download('punkt')
nltk.download('stopwords')
sw=nltk.corpus.stopwords.words("english")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
# df = pd.read_csv("New_Dropped_Uscomments.csv",error_bad_lines=False)
df = pd.read_csv("New_DF_Positive_Negative_Netural_dropna.csv",error_bad_lines=False)
# df = pd.read_csv("Random_same_sample_ALL_3_Category.csv",error_bad_lines=False)

C:\Users\LENOVO\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3552: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


In [6]:
df.head()


video_id                                       comment_text  likes  \
0  XpVt6Z1Gjjo                  Logan Paul it's yo big day ‼️‼️‼️      4   
1  XpVt6Z1Gjjo  I've been following you from the start of your...      3   
2  XpVt6Z1Gjjo                 Say hi to Kong and maverick for me      3   
3  XpVt6Z1Gjjo                                MY FAN . attendance      3   
4  XpVt6Z1Gjjo                                         trending 😉      3   

   replies  Polarity   Target  
0        0       0.0  Neutral  
1        0       0.0  Neutral  
2        0       0.0  Neutral  
3        0       0.0  Neutral  
4        0       0.0  Neutral

In [7]:
len(df)

471631

In [8]:
df['Target'].value_counts()

Positive    203102
Neutral     195920
Negative     72609
Name: Target, dtype: int64

# Trying Only Positive and Negative

In [9]:
from textblob import TextBlob

In [10]:
polarity = []
for comment in df['comment_text']:
    try:
        polarity.append(TextBlob(comment).sentiment.polarity)
    except:
        polarity.append(0)

In [11]:
x=[]
for i in df.Polarity:
    if i>0:
        x.append('Positive')
    elif i<0:
        x.append('Negative')
    else:
        x.append('Neutral')
        

In [12]:
df['Target'] = x

In [13]:
df.head()

video_id                                       comment_text  likes  \
0  XpVt6Z1Gjjo                  Logan Paul it's yo big day ‼️‼️‼️      4   
1  XpVt6Z1Gjjo  I've been following you from the start of your...      3   
2  XpVt6Z1Gjjo                 Say hi to Kong and maverick for me      3   
3  XpVt6Z1Gjjo                                MY FAN . attendance      3   
4  XpVt6Z1Gjjo                                         trending 😉      3   

   replies  Polarity   Target  
0        0       0.0  Neutral  
1        0       0.0  Neutral  
2        0       0.0  Neutral  
3        0       0.0  Neutral  
4        0       0.0  Neutral

In [62]:
df['Target'].value_counts()

Positive    203102
Neutral     195920
Negative     72609
Name: Target, dtype: int64

In [63]:
tmp_positive = df[df['Target']=='Positive'].sample(50000)
tmp_negative = df[df['Target']=='Negative'].sample(50000)
tmp_netural = df[df['Target']=='Neutral'].sample(50000)

In [64]:
df1 = pd.concat([tmp_positive,tmp_negative,tmp_netural],ignore_index=True)

In [65]:
df1.head()

video_id                                       comment_text  likes  \
0  nJSrCX1U1hg                        Jezus that is really bigggg      0   
1  7_HboVYEkWw  Never had this sauce but I'm thinking if you t...      0   
2  ErWde9LVg0A  Seriously love you Manny! My favorite MUA!! Ke...      0   
3  7wsYiuNERZA  Zelda film? Yes, I can see it happening one da...      0   
4  Ty7YYxfFRtA                                             *Nice*      0   

   replies  Polarity    Target  
0        0  0.200000  Positive  
1        0  0.262500  Positive  
2        0  0.426563  Positive  
3        0  0.136017  Positive  
4        0  0.600000  Positive

In [18]:
# TextBlob(df1['comment_text'][2]).polarity

0.5

In [29]:
# ans=0
# for i in list(TextBlob(df1['comment_text'][3]).words):
#     print(i)
#     ans+=TextBlob(i).polarity
    
# ans

You
have
great
lips😊


0.8

In [66]:
df1['Target'].value_counts()

Positive    50000
Negative    50000
Neutral     50000
Name: Target, dtype: int64

In [67]:
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import *
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [68]:
sw = stopwords.words('english')
ps = PorterStemmer()
lemmatizer = nltk.stem.WordNetLemmatizer()

In [69]:
# df['tokenize'] = df['comment_text'].apply()

In [70]:
df1['comment_text'][3]

"Zelda film? Yes, I can see it happening one day. Good luck to the folks  who have to pitch it. But I think a LOT of when (if)it gets a greenlight will depend on the upcoming Tomb Raider film. Why? Because it's a film based off a video gae. And for the most part, game to films don't have a high batting average...\\n\\nanime films to live action? Man, still hope the LA version o Akira makes the finish line. But yeah, Ghost In The Shell had some high points, but in y view had more low ones. And Shell, as pointed out, was a box office disappointment domestically. Death Note was a letdown (go see the LA Japanese version instead folks)...but here's y thinking. Back in 2002, I saw on a big screen at the Austin Film Fest, Cowboy Bebop The Movie. Sold out. It was so popular they had to add another screening. And yes, I loved every damn minute of it. Then I think of Hayao Miyazaki's  Spirited Away and...maybe, just maybe J amine should just be left alone and released domestically or on Netflix/

In [71]:
str=df1['comment_text'][3]

In [72]:
tb = TextBlob(str)


In [73]:
tb.polarity

0.13601731601731604

In [74]:
lst = tb.words

In [75]:
lst

WordList(['Zelda', 'film', 'Yes', 'I', 'can', 'see', 'it', 'happening', 'one', 'day', 'Good', 'luck', 'to', 'the', 'folks', 'who', 'have', 'to', 'pitch', 'it', 'But', 'I', 'think', 'a', 'LOT', 'of', 'when', 'if', 'it', 'gets', 'a', 'greenlight', 'will', 'depend', 'on', 'the', 'upcoming', 'Tomb', 'Raider', 'film', 'Why', 'Because', 'it', "'s", 'a', 'film', 'based', 'off', 'a', 'video', 'gae', 'And', 'for', 'the', 'most', 'part', 'game', 'to', 'films', 'do', "n't", 'have', 'a', 'high', 'batting', 'average', 'n\\nanime', 'films', 'to', 'live', 'action', 'Man', 'still', 'hope', 'the', 'LA', 'version', 'o', 'Akira', 'makes', 'the', 'finish', 'line', 'But', 'yeah', 'Ghost', 'In', 'The', 'Shell', 'had', 'some', 'high', 'points', 'but', 'in', 'y', 'view', 'had', 'more', 'low', 'ones', 'And', 'Shell', 'as', 'pointed', 'out', 'was', 'a', 'box', 'office', 'disappointment', 'domestically', 'Death', 'Note', 'was', 'a', 'letdown', 'go', 'see', 'the', 'LA', 'Japanese', 'version', 'instead', 'folks', 

In [34]:
# ans=0
# for i in lst:
#     print(i)
#     new_tb = TextBlob(i)
#     ans += new_tb.polarity
#     print(ans)
# #     print(new_tb.polarity)
# ans

In [76]:
df1.head()

video_id                                       comment_text  likes  \
0  nJSrCX1U1hg                        Jezus that is really bigggg      0   
1  7_HboVYEkWw  Never had this sauce but I'm thinking if you t...      0   
2  ErWde9LVg0A  Seriously love you Manny! My favorite MUA!! Ke...      0   
3  7wsYiuNERZA  Zelda film? Yes, I can see it happening one da...      0   
4  Ty7YYxfFRtA                                             *Nice*      0   

   replies  Polarity    Target  
0        0  0.200000  Positive  
1        0  0.262500  Positive  
2        0  0.426563  Positive  
3        0  0.136017  Positive  
4        0  0.600000  Positive

In [77]:
df1['comment_text'] = df1['comment_text'].str.lower()

In [78]:
df1 = df1.drop(['video_id','likes','replies'],axis=1)

In [79]:
df1.head()

comment_text  Polarity    Target
0                        jezus that is really bigggg  0.200000  Positive
1  never had this sauce but i'm thinking if you t...  0.262500  Positive
2  seriously love you manny! my favorite mua!! ke...  0.426563  Positive
3  zelda film? yes, i can see it happening one da...  0.136017  Positive
4                                             *nice*  0.600000  Positive

In [80]:
def remove_sw_punc(str):
    new_str=[]
    for i in list(TextBlob(str).words):
        if i not in stopwords.words('english') and i not in string.punctuation:
#             print(i)
            new_str.append(i)
    text = ' '.join(new_str)
    return text

In [81]:
str="Best thing ever seen yet. 1:00 wants to play with the toy too. No  cat goes ohh..."
def tokenize(str):
    tb = TextBlob(str).words
    
    return list(tb)
    
#     print(tb)
#     print(type(tb))

In [82]:
df1['comment_text'] = df1['comment_text'].apply(remove_sw_punc)

KeyboardInterrupt: 

In [ ]:
df1.head()

In [52]:
# df1['comment_text'] = df1['comment_text'].apply(tokenize)

In [31]:
tokenize(str)

['Best',
 'thing',
 'ever',
 'seen',
 'yet',
 '1:00',
 'wants',
 'to',
 'play',
 'with',
 'the',
 'toy',
 'too',
 'No',
 'cat',
 'goes',
 'ohh']

In [97]:
from sklearn.feature_extraction.text import CountVectorizer

In [98]:
vectorizer = CountVectorizer()

In [99]:
X = vectorizer.fit_transform(tb).toarray()

In [105]:
print(X)
X.reshape(1,len(X.shape)).shape

[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]]


ValueError: cannot reshape array of size 289 into shape (1,2)

In [32]:
def polarity(str):
    tb = TextBlob(str)
    return tb.polarity

In [33]:
df1['New_Target'] = df1['comment_text'].apply(polarity)

In [34]:
def lable_target_no(no):
    if no>0:
        return 1
    elif no<0:
        return -1
    else:
        return 0

In [35]:
df1.head()

video_id                                       comment_text  likes  \
0  Ez95rPffd8k         Hahaha E! News are retarded. Love you Jim!      0   
1  x9VBzdkHMBU                             the guy was sooo. cute      0   
2  Lwn97mpBCu8  If you want to turn it up a notch, saute some ...      0   
3  N_zDcuX1Y54  We have Zwitsal here ini Indonesia. It was my ...      0   
4  RbXYadQw1C4  maybe you can't love someone until you love yo...      0   

   replies  Polarity    Target  New_Target  
0        0  0.025000  Positive    0.025000  
1        0  0.500000  Positive    0.500000  
2        0  1.000000  Positive    1.000000  
3        0  0.750000  Positive    0.750000  
4        0  0.441071  Positive    0.441071

In [36]:
df1['Target_in_no'] = df1['New_Target'].apply(lable_target_no)

In [37]:
df1['Target_in_no'].value_counts()

 1    70000
-1    70000
 0    70000
Name: Target_in_no, dtype: int64

In [38]:
df1 = df1.drop(['video_id'],axis=1)

In [39]:
df1.head()

comment_text  likes  replies  \
0         Hahaha E! News are retarded. Love you Jim!      0        0   
1                             the guy was sooo. cute      0        0   
2  If you want to turn it up a notch, saute some ...      0        0   
3  We have Zwitsal here ini Indonesia. It was my ...      0        0   
4  maybe you can't love someone until you love yo...      0        0   

   Polarity    Target  New_Target  Target_in_no  
0  0.025000  Positive    0.025000             1  
1  0.500000  Positive    0.500000             1  
2  1.000000  Positive    1.000000             1  
3  0.750000  Positive    0.750000             1  
4  0.441071  Positive    0.441071             1

In [41]:
# df1['Tokenize_word'] = df1['comment_text'].apply(tokenize)

In [42]:
df1.head()

comment_text  likes  replies  \
0         Hahaha E! News are retarded. Love you Jim!      0        0   
1                             the guy was sooo. cute      0        0   
2  If you want to turn it up a notch, saute some ...      0        0   
3  We have Zwitsal here ini Indonesia. It was my ...      0        0   
4  maybe you can't love someone until you love yo...      0        0   

   Polarity    Target  New_Target  Target_in_no  
0  0.025000  Positive    0.025000             1  
1  0.500000  Positive    0.500000             1  
2  1.000000  Positive    1.000000             1  
3  0.750000  Positive    0.750000             1  
4  0.441071  Positive    0.441071             1

In [43]:
# df1 = df1.drop(['Tokenize_word'],axis=1)

In [44]:
# df1.head()

In [45]:
# df1['comment_text'] = df1['comment_text'].str.lower()

In [46]:
df1.head()

comment_text  likes  replies  \
0         hahaha e! news are retarded. love you jim!      0        0   
1                             the guy was sooo. cute      0        0   
2  if you want to turn it up a notch, saute some ...      0        0   
3  we have zwitsal here ini indonesia. it was my ...      0        0   
4  maybe you can't love someone until you love yo...      0        0   

   Polarity    Target  New_Target  Target_in_no  
0  0.025000  Positive    0.025000             1  
1  0.500000  Positive    0.500000             1  
2  1.000000  Positive    1.000000             1  
3  0.750000  Positive    0.750000             1  
4  0.441071  Positive    0.441071             1

In [48]:
# df1['Target_in_no'].value_counts()

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [50]:
countvector=CountVectorizer(ngram_range=(2,2))


In [51]:
x=countvector.fit_transform(df1['comment_text'])
y = df1['Target_in_no']

In [52]:
x_train1,x_test1,y_train1,y_test1=train_test_split(x,y,test_size=0.3,random_state=101)

In [ ]:
# model1=MultinomialNB()

In [53]:
x_train1.shape

(147000, 946655)

In [54]:
x_test1.shape

(63000, 946655)

In [ ]:
# implement RandomForest Classifier
randomclassifier=RandomForestClassifier(n_estimators=100,criterion='entropy')
randomclassifier.fit(x_train1,y_train1)

In [ ]:
y_pred = randomclassifier.predict(x_test1)